### ISSUE TITLE
Make uniqueness check optional?

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-py#196]
_From @akariv_ 

However, I wonder if it's the right way to go. For large datasets, this implementation would take lots of memory - especially for large primary keys. Performance wise, we will also see a degradation in large datasets as we move through the rows.

Because it can have these unwanted (and unexpected) side-effects, I would make this entire check optional - that is, off by default.

---

_From @akariv_ 

Also - perhaps we could tie this in with the strict parameter?
At the moment I see that the strict parameter in the Table constructor is not used (is that on purpose?), so we can safely add that meaning to it (strict == extra validation checks, e.g. uniqueness).
wdyt?

**Comment by roll** [comment]
@akariv 
I think here could be a problem only with a memory. We use `set()` for values cache and it's theoretically O(1). I have no preference to have this check by default or don't have it but just afraid to get into a premature optimization. So please let me know if you're sure we need to disable it by default.

**Comment by mjos** [comment]
Hi, I agree with @akariv, that the performance for large datasets is quite bad due to validation being tied with reading, especially when debugging. Our dataset consist of cca 50.000 records and when the dataset is being loaded in debugging session in PyCharm we have to wait cca 4 minutes on each iteration. Of course we could parse out CSV meta information from datapackage.json, and then read the data directly using csv module, but this would be against the wonderful idea of resource abstraction in datapackage.py. I suggest to make validation in reading optional. What do you think?

**Comment by roll** [comment]
@mjos 
It's definitely a problem based on your use case..

As a quick fix - have you tried to use `Resource/Table.iter(cast=false)` to disable those checks?

**Comment by mjos** [comment]
@roll, No, thanks for pointing this out, I'll check it out. An thanks for the quick reply.

**Comment by roll** [comment]
Unique checks are made configurable in [Frictionless Framework](https://github.com/frictionlessdata/tableschema-py#tableschema-py)
